### 启动端口号
server:
  port: 8088
### 设置数据库
spring:
#    datasource:
#      driver-class-name: org.h2.Driver
#      schema: classpath:db/schema-h2.sql
#      data: classpath:db/data-h2.sql
#      url: jdbc:h2:mem:test
#      username: root
#      password: test

  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/netcommand?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: admin
    password: admin123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
# 配置slq打印日志
mybatis-plus:
  typeEnumsPackage:  com.baomidou.mybatisplus.samples.quickstart.enumutil
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)