### 启动端口号
server:
  port: 8088
### 设置数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zp_self?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: admin
    password: admin123
### 配置mybatisPlus
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在src/main/resource目录 classpath:/mapper/*/*Mapper.xml
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zpself.module.**.entity
  global-config:
    db-config:
      #主键类型  AUTO(0):"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #db-column-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: zlp_
      #数据库大写下划线转换
      #capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器typeEnumsPackage
    refresh: true
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.pci.mics.handler.MyMetaObjectHandler